【集いで練習する用のプルリクです】２点追加
nosenami/challengerTrialProject pull request #2
Opened 2023-08-19 09:43 UTC by nosenami

内容を２点追加しました。
誤りがあったら指摘のほどお願いいたします。

2023-09-05 08:56 UTC, h-yokoyama-eiwa requested changes
@nosenami 
コメントしました。

2023-09-05 08:56 UTC, h-yokoyama-eiwa commented on 文章フォルダ/ことわざ一覧.md
> +ヒント：https://gogen-yurai.jp/nasakewahitonotamenarazu/
違いますよ

2023-09-05 08:56 UTC, h-yokoyama-eiwa commented on 文章フォルダ/ことわざ一覧.md
> +ヒント；https://gogen-yurai.jp/kigaokenai/
違いますよ

2023-09-12 08:51 UTC, k-shimada-esm approved these changes
確認してね

2023-09-12 08:51 UTC, k-shimada-esm commented on 文章フォルダ/ことわざ一覧.md
>  なにかをしようと思いついたら、すぐに実行したほうがいいというたとえ。
ああああああああ

2023-09-12 08:51 UTC, k-shimada-esm commented on 文章フォルダ/ことわざ一覧.md
> +### 情けは人の為ならず
あああああ２

2023-09-12 08:58 UTC, ma-miyagawa reviewed
コメント

2023-09-12 08:58 UTC, ma-miyagawa commented on 文章フォルダ/ことわざ一覧.md
>  ### 思い立ったが吉日
eeeeeeee

2023-09-12 09:00 UTC, merged